### ISSUE TITLE
Merge VoidFinder and Vsquared python package

### ISSUE THREAD

**Issue by lavaux** [DESI-UR/VAST#50]
The two components of VAST are installable as two packages. This effectively prevents the use of `pip install` directly on the repository such as:
```
pip install git+https://github.com/DESI-UR/VAST
```
and thus does not follow common practice. It also slightly confuses a user to have two pip installable packages that fills up the namespace `vast` though through two different subpackages.

Could the files `setup.py` be adjusted so that there is only one needed at the top of the source tree to satisfy this constraint?

Reviewing https://github.com/openjournals/joss-reviews/issues/4033

**Comment by QuiteAFoxtrot** [comment]
Yeah we can take a look

**Comment by kadglass** [comment]
We purposefully set up VAST so that each void-finding method could be installed separately, giving the user the flexibility to only install one if preferred.  If this is too confusing, or if this ability to install the package using this particular method of `pip install` is necessary, then we can reconsider the VAST package structure.

**Comment by sybenzvi** [comment]
We did consider setting up VAST as a single package but ultimately settled on separate build systems that could then be set up as separate packages in pip:
- `pip install vast-voidfinder`
- `pip install vast-vsquared`
- ...

But I think it's not well documented, and we may have set ourselves up for more difficult maintenance in the future. Merging it into one package would require restructuring the repository, though I suspect it won't be a huge amount of work; probably a weekend afternoon. I'd be in favor of this.

**Comment by lavaux** [comment]
Indeed for clarity and long term maintenance I would be in favor of the merging this into one package.

**Comment by sybenzvi** [comment]
@kadglass, I did the reorganization and made a PR (#53). Note that you'll see complaints about the unit tests failing, but this is because I deleted the old CircleCI tests in favor of using GitHub Actions, which will make them easier to maintain going forward. I checked the unit tests separately and they definitely work.
