### ISSUE TITLE
Sample script for finding voids from the mock galaxy catalogue

### ISSUE THREAD

**Issue by mrhossen38** [DESI-UR/VAST#55]
Hi,
Excellent repo. It seems that everything is in one package. I am just wondering whether is it possible to add a sample script for finding voids (both cases: VoidFinders and V2) from the mock galaxy catalogue (without any cut)? Thanks.

**Comment by kadglass** [comment]
We just finished restructuring the repo and have moved the sample scripts to a top-level directory so that they are easier to locate.

For VoidFinder, see the `SDSS_VoidFinder_dr7.py` file, which contains a working example script for using VoidFinder with the included galaxy catalog.  All cuts made to the input catalog are implemented in the `filter_galaxies` function.  If, for example, you do not want to implement a magnitude cut, you would set the `mag_cut` kwarg to False.  The main options that are available are included as comments in the beginning of this script.  See the documentation at [https://vast.readthedocs.io/en/latest/VoidFinder_functions.html#filter-galaxies](https://vast.readthedocs.io/en/latest/VoidFinder_functions.html#filter-galaxies) for more details.

Vsquared uses a configuration file for setting the various input parameters.  Also included in the example_scripts directory is `DR7_config.ini` file, which contains the various options for running Vsquared on the included galaxy catalog.  See the included comments and the documentation at [https://vast.readthedocs.io/en/latest/Vsquared_examples.html#configuration-file-options](https://vast.readthedocs.io/en/latest/Vsquared_examples.html#configuration-file-options) for more details.

If you are looking for something else, please let us know!

**Comment by mrhossen38** [comment]
Thanks @kadglass for your detailed response. I got my answer.
